#!/usr/bin/env bash


# Keybindings

mutter_wlnd_keys="org.gnome.mutter.wayland.keybindings"
gsettings set "$mutter_wlnd_keys" restore-shortcuts "[]"
gsettings set "$mutter_wlnd_keys" switch-to-session-1 "[]"
gsettings set "$mutter_wlnd_keys" switch-to-session-2 "[]"
gsettings set "$mutter_wlnd_keys" switch-to-session-3 "[]"
gsettings set "$mutter_wlnd_keys" switch-to-session-4 "[]"
gsettings set "$mutter_wlnd_keys" switch-to-session-5 "[]"
gsettings set "$mutter_wlnd_keys" switch-to-session-6 "[]"
gsettings set "$mutter_wlnd_keys" switch-to-session-7 "[]"
gsettings set "$mutter_wlnd_keys" switch-to-session-8 "[]"
gsettings set "$mutter_wlnd_keys" switch-to-session-9 "[]"
gsettings set "$mutter_wlnd_keys" switch-to-session-10 "[]"
gsettings set "$mutter_wlnd_keys" switch-to-session-11 "[]"
gsettings set "$mutter_wlnd_keys" switch-to-session-12 "[]"


mutter_keys="org.gnome.mutter.keybindings"
gsettings set "$mutter_keys" cancel-input-capture "[]"
gsettings set "$mutter_keys" rotate-monitor "[]"
gsettings set "$mutter_keys" switch-monitor "[]"
gsettings set "$mutter_keys" toggle-tiled-left "[]"
gsettings set "$mutter_keys" toggle-tiled-right "[]"


shell_keys="org.gnome.shell.keybindings"
gsettings set "$shell_keys" screenshot "[]"
gsettings set "$shell_keys" screenshot-window "['<Alt>Print']"
gsettings set "$shell_keys" show-screenshot-ui "[]"
gsettings set "$shell_keys" show-screen-recording-ui "[]"

gsettings set "$shell_keys" toggle-application-view "['<Super>a']"
gsettings set "$shell_keys" toggle-message-tray "[]"
gsettings set "$shell_keys" toggle-quick-settings "[]"
gsettings set "$shell_keys" toggle-overview "[]"

gsettings set "$shell_keys" focus-active-notification "[]"

gsettings set "$shell_keys" shift-overview-down "[]"
gsettings set "$shell_keys" shift-overview-up "[]"

gsettings set "$shell_keys" open-new-window-application-1 "[]"
gsettings set "$shell_keys" open-new-window-application-2 "[]"
gsettings set "$shell_keys" open-new-window-application-3 "[]"
gsettings set "$shell_keys" open-new-window-application-4 "[]"
gsettings set "$shell_keys" open-new-window-application-5 "[]"
gsettings set "$shell_keys" open-new-window-application-6 "[]"
gsettings set "$shell_keys" open-new-window-application-7 "[]"
gsettings set "$shell_keys" open-new-window-application-8 "[]"
gsettings set "$shell_keys" open-new-window-application-9 "[]"

gsettings set "$shell_keys" switch-to-application-1 "[]"
gsettings set "$shell_keys" switch-to-application-2 "[]"
gsettings set "$shell_keys" switch-to-application-3 "[]"
gsettings set "$shell_keys" switch-to-application-4 "[]"
gsettings set "$shell_keys" switch-to-application-5 "[]"
gsettings set "$shell_keys" switch-to-application-6 "[]"
gsettings set "$shell_keys" switch-to-application-7 "[]"
gsettings set "$shell_keys" switch-to-application-8 "[]"
gsettings set "$shell_keys" switch-to-application-9 "[]"


wm_keys="org.gnome.desktop.wm.keybindings"
gsettings set "$wm_keys" switch-input-source "['<Alt>Shift_L']"
gsettings set "$wm_keys" switch-input-source-backward "[]"

gsettings set "$wm_keys" panel-run-dialog "['<Alt>F2']"

gsettings set "$wm_keys" close "['<Alt>F4', '<Super>w']"
gsettings set "$wm_keys" activate-window-menu "[]"
gsettings set "$wm_keys" toggle-maximized "[]"
gsettings set "$wm_keys" always-on-top "[]"
gsettings set "$wm_keys" toggle-on-all-workspaces "[]"
gsettings set "$wm_keys" toggle-above "[]"
gsettings set "$wm_keys" toggle-fullscreen "['']"

gsettings set "$wm_keys" switch-to-workspace-left "['']"
gsettings set "$wm_keys" switch-to-workspace-right "['']"
gsettings set "$wm_keys" switch-to-workspace-down "[]"
gsettings set "$wm_keys" switch-to-workspace-up "[]"
gsettings set "$wm_keys" switch-to-workspace-1 "['']"
gsettings set "$wm_keys" switch-to-workspace-2 "['']"
gsettings set "$wm_keys" switch-to-workspace-3 "['']"
gsettings set "$wm_keys" switch-to-workspace-4 "['']"
gsettings set "$wm_keys" switch-to-workspace-5 "['']"
gsettings set "$wm_keys" switch-to-workspace-6 "['']"
gsettings set "$wm_keys" switch-to-workspace-7 "['']"
gsettings set "$wm_keys" switch-to-workspace-8 "['']"
gsettings set "$wm_keys" switch-to-workspace-9 "['']"
gsettings set "$wm_keys" switch-to-workspace-10 "[]"
gsettings set "$wm_keys" switch-to-workspace-11 "[]"
gsettings set "$wm_keys" switch-to-workspace-12 "[]"
gsettings set "$wm_keys" switch-to-workspace-last "['']"

gsettings set "$wm_keys" move-to-workspace-right "['']"
gsettings set "$wm_keys" move-to-workspace-left "['']"
gsettings set "$wm_keys" move-to-workspace-down "[]"
gsettings set "$wm_keys" move-to-workspace-up "[]"
gsettings set "$wm_keys" move-to-workspace-1 "['']"
gsettings set "$wm_keys" move-to-workspace-2 "['']"
gsettings set "$wm_keys" move-to-workspace-3 "['']"
gsettings set "$wm_keys" move-to-workspace-4 "['']"
gsettings set "$wm_keys" move-to-workspace-5 "['']"
gsettings set "$wm_keys" move-to-workspace-6 "['']"
gsettings set "$wm_keys" move-to-workspace-7 "['']"
gsettings set "$wm_keys" move-to-workspace-8 "['']"
gsettings set "$wm_keys" move-to-workspace-9 "['']"
gsettings set "$wm_keys" move-to-workspace-10 "[]"
gsettings set "$wm_keys" move-to-workspace-11 "[]"
gsettings set "$wm_keys" move-to-workspace-12 "[]"
gsettings set "$wm_keys" move-to-workspace-last "[]"
